# Usar a imagem node:16.14-alpine como base
FROM node:16.14-slim

# Mudar para o diretório de trabalho /app-backend
WORKDIR /app-backend

# Copiar os package.json, package-lock.json e packages.npm para o container
COPY . .

# Instalar as dependências Node
RUN npm install
# Copiar o restante dos arquivos da aplicação para o container

# Sinalize que aplicação expõe a porta 3001

# Configurar os comandos para iniciar a aplicação de acordo com as boas práticas
# Dica: Leia a seção Docker e Docker-compose no README para mais informações
CMD ["npm", "run", "start"]